plugins:
  - '@remotion'

extends:
  - xo
  - xo-typescript
  - xo-react
  - plugin:react/jsx-runtime # Prevents "'React' must be in scope when using JSX" errors
  - plugin:tailwindcss/recommended
  - plugin:@remotion/recommended
