on:
  workflow_dispatch:
    inputs:
      video:
        description: Video to render
        required: true
        type: choice
        options: 
          - dna-horizontal-60fps-1920x1080
          - dna-horizontal-30fps-960x540
          - dna-vertical-60fps-1080x1920
          - dna-vertical-30fps-540x960
          - carbonized-horizontal-60fps-1920x1080
          - carbonized-horizontal-30fps-960x540
          - carbonized-vertical-60fps-1080x1920
          - carbonized-vertical-30fps-540x960
          - crush-horizontal-60fps-1920x1080
          - crush-horizontal-30fps-960x540
          - crush-vertical-60fps-1080x1920
          - crush-vertical-30fps-540x960

env:
  NODE_VERSION: 18

name: Render
jobs:
  render:
    name: Render - ${{ inputs.video }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Node.js dependencies
        run: npm ci
      - name: Render
        run: npm run render --video=${{ inputs.video }}
      - name: Upload rendered video artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
